### ISSUE TITLE
Signup cant redirect to /discover

### ISSUE THREAD

**Issue by BaileyM96** [BaileyM96/Love.Dev#42]
Steps to reproduce problem:

1: Start up the server in terminal
2: Choose signup and fill out the required form to create your account
3: Click signup afterwards

Expected outcome:
After clicking signup and creating account it should redirect you to the discover page to start liking/disliking users

**Comment by Czaldivar419** [comment]
Issue has been rectified. New users are now redirected to the /discover page after a successful signup.
