### ISSUE TITLE
Need to design the profile card

### ISSUE THREAD

**Issue by BaileyM96** [BaileyM96/Love.Dev#48]
Issue: 

Profile page/component has no styling for the inputs

Steps to reproduce problem: 

1: Login into your account 

2: On explore page navigate to the small user icon and open it up, this brings you to the user profile

* Reference the styling of explore page, and user.js component!

Reach out to Bailey or Christian if you have any questions.

**Comment by Czaldivar419** [comment]
Profile card now virtually identical to the discover card.
